pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Samoth1/MilkStgo']])
                dir("MilkStgoPayment"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("MilkStgoPayment"){
                    sh "mvn test"
                }
            }
        }
        stage("SonarQube Analysis"){
            steps{
                dir("MilkStgoPayment"){
                    sh "mvn clean verify sonar:sonar -Dsonar.projectKey=milkstgo -Dsonar.projectName='milkstgo' -Dsonar.host.url=http://localhost:9000 -Dsonar.token=sqp_d71bba36547e81fd9584e4eb71f12f4e97ff3aab"
                }
            }
        }
        stage("Build Docker Image"){
            steps{
                dir("MilkStgoPayment"){
                    sh "docker build -t samoth1/milkstgo ."
                }
            }
        }
        stage("Push Docker Image"){
            steps{
                dir("MilkStgoPayment"){
                    withCredentials([string(credentialsId: 'dckrhubpassword', variable: 'dckpass')]) {
                        sh "docker login -u samoth1 -p ${dckpass}"
                    }
                    sh "docker push samoth1/milkstgo"
                }
                
            }
        }
    }
    post{
        always{
            dir("MilkStgoPayment"){
                sh "docker logout"
            }
        }
    }
}